# Enable sponsoring options (uncomment and configure as appropriate)
# github: ["chethanyadav456"]
# patreon: ""
# open_collective: ""
# ko_fi: ""
# liberapay: ""
# issuehunt: ""
# custom: ["https://your-custom-sponsor-link.example"]
